### ISSUE TITLE
output BLZTRP.tau_k for optdriver=7

### ISSUE THREAD

**Issue by goodwilling** [abinit/abinit#38]
Hi.  In electron-phonon coupling calculation with optdriver=7, there are output of TAU(eKS) 
in the standard output file as follows: 

TAU(eKS): Lifetime in femtoseconds computed at the KS energy.

...
K-point: [ 0.0000E+00,  0.0000E+00,  0.0000E+00], T:  300.0 [K], mu_e:    1.384
   B    eKS    SE2(eKS)  TAU(eKS)  DeKS
  10  -2.712    0.080      4.1    0.000
...

However,  with the option "prtbltztrp 1"  we cannot get the output file BLZTRP.tau_k.

Since TAU(eKS) is calculated with optdriver=7, it is strongly desired to get output file
BLZTRP.tau_k together with other BoltzTraP-related files. 

Thank you very much.

**Comment by gbrunin** [comment]
Dear goodwilling,

Thank you for your interest in our driver ! We appreciate any feedback on these new features. 

One should be careful when using the lifetimes computed by ABINIT in BoltzTraP (BTP). Indeed, the BTP interpolation requires the band energy (or the lifetime) on the complete band, for all the k-points in the IBZ. Unless you used a very large sigma_erange (which is not recommended for transport properties), this is typically not the case. One could try to interpolate with BTP by setting arbitrary values outside the energy window, but this could lead to spurious effects in the interpolation of the lifetimes inside the energy window and should be carefully tested. In other words, the interpolation within the important energy window could be bad because of the lack of data outside the window. We prefer to avoid printing the lifetimes in the BTP format to avoid wrong results or bugs on the user side.

For this reason, we decided to use our own transport driver to compute the mobility, Seebeck coefficient, and so on, and strongly recommend to use this driver for transport properties using the previously computed lifetimes. This driver is run automatically after the SIGEPH.nc file has been completed, or it can be ran separately by setting eph_task 7. You can check the eph4mob tutorial for more details: https://docs.abinit.org/tutorial/eph4mob/#transport-calculation-from-sigephnc

Let us know if you have any further comments.

Best, 
Guillaume

**Comment by goodwilling** [comment]
Sorry for late response.
I have studied the eph4mob tutorial, obtained the electron mobility, and am trying to set up my own calculations of small systems. Thank you very much.
Now I have been curious on the following subjects: 
(1) The calculations seem to be heavy and require much disk spaces.  Is it possible to calculate some systems larger than those in the paper (PhysRevB.102.094308, 2020) , for example,  tens of atoms or even larger (>100 atoms) with 
the use of supercomputers?
(2)  Is it possible to get the correct order of electron mobility of wide-gap (~7eV) insulators? I was told that although the electronic conductivity of an insulator is very small, it could not be zero if used for some specific devices. 
Thank you very much.

**Comment by gbrunin** [comment]
Hi goodwilling,

(1) We managed to run mobility computations for systems up to 20 atoms without major issues. Of course, we use supercomputers, since these remain demanding computations. We were also able to compute the mobility for a 40-atoms system. We have not yet tried larger systems. We typically reach a similar limit as the other softwares developed to compute the phonon-limited mobility, one should not expect to be able to get it for systems with more than 100 atoms for the time being. 
To reduce the walltime and memory, make sure to use mixprec 1, boxcutmin (as low as 1.1), and sigma_erange (typically < 0.25 eV at 300 K). 
(2) The mobility and conductivity are different quantities. If you want to compute the mobility, you can set the carrier concentration to a low value (but not too low), such as 1e15 cm^-3 (eph_extrael, be careful with the units). In an undoped insulator, it would be much lower, but it does not matter for the mobility, as long as the Fermi level remains far enough from the band edges (as shown in the supplemental material of our PRB). For the conductivity, you can try to obtain it without doping the system, but I fear the Fermi level will be so far from the band edges that it will lead to numerical instabilities in the computation of the transport quantities. We did not test that with a large band gap system. Note that I'm not sure that insulators that must have a small conductivity are not doped, and if they are, you can simulate that by specifying the carrier concentration in the input file. 

Best,
Guillaume
