### ISSUE TITLE
Why Fermi level 5.108 in Aluminium?

### ISSUE THREAD

**Issue by sportmasterofficial** [abinit/abinit#47]
Hello all! I try to calculate dos and band structure of Aluminum with abinit, i am new here. But when i look on results, i see that i have wrong dos and wrong band structure, i am compare with another result which i getting with wien2k
![Снимок экрана 2021-08-12 в 19 17 09](https://user-images.githubusercontent.com/82897774/129240851-e640cace-4cfe-4254-9154-4d8e472c244d.png)
And when i looking in .GSR file i see that Fermi level shift on 5.108 eV
![Снимок экрана 2021-08-12 в 20 25 38](https://user-images.githubusercontent.com/82897774/129241275-93cc425e-8fff-49a7-819b-5a5965df2ae1.png)
Why is this happening?

my input file: 
```
#Definition of the unit cell
ndtset 2
acell 3*7.632471437073 
natom    1  
ntypat   1  
typat    1  
znucl    13  

xred     0.000000000000000   0.000000000000000   0.000000000000000 

rprim  0.0  0.5  0.5   # FCC primitive vectors (to be scaled by acell)
       0.5  0.0  0.5
       0.5  0.5  0.0

#pseudos "paw/Al.GGA_PBE-JTH.xml"
pseudos "psp/Al.psp8"
ecut 20.0
nstep 20
#pawecutdg 50.

#Dataset 1 : usual self-consistent calculation
kptopt1 1          

ngkpt1  8 8 8
prtden1  1         # Print the density, for use by dataset 2
tolwfr1  1.0d-10    
nshiftk1 4
shiftk1  0.5 0.5 0.5  
         0.5 0.0 0.0
         0.0 0.5 0.0
         0.0 0.0 0.5
#Dataset 2 : the band structure
iscf2    -2
getden2  -1
kptopt2  -4  
nband2   9
ndivsm2   10   

kptbounds2  
            +0.50000  +0.25000  +0.75000  # W
            +0.00000  +0.00000  +0.00000  # $\Gamma$
            +0.50000  +0.00000  +0.50000  # X
            +0.50000  +0.25000  +0.75000  # W
            +0.37500  +0.37500  +0.75000  # K
            
            
           
tolwfr2  1.0d-12
enunit2  1             # Will output the eigenenergies in eV

```
Thanks attention!

**Comment by gmatteo** [comment]
Only energy differences have physical meaning as you can always add a constant term  to the Hamiltonian without changing the physics.
In the Wien2k band structure the Fermi level is **arbitrarily**  set to zero for visualization purposes. 
You can obtain the same result in the abipy plot_with_edos method if you don't specify `e0` since the default value for e0 is "fermie" that is "shift all eigenvalues and the DOS to have zero energy at the Fermi energy."

**Comment by sportmasterofficial** [comment]
Well your advice helped me for the band structure. but DOS is still different![image](https://user-images.githubusercontent.com/82897774/129402679-c81402ae-39fd-4c94-a1aa-0b5be326ae05.jpeg)

**Comment by gmatteo** [comment]
Your abinit dos has been computed with a 8x8x8 k-mesh and four shifts.
Very likely this k-sampling is too coarse to resolve the fine details. 
Besides `get_edos` computes the DOS with the a Gaussian smearing of 0.2 eV:

```
def get_edos(self, method="gaussian", step=0.1, width=0.2):
```

In order to improve the agreement with Wien2k, you may try to increase the k-sampling for the DOS and/or decrease the value of width.

**Comment by sportmasterofficial** [comment]
Thank you! I did try with 20x20x20 k-mesh and took different meanings of width, I didn't get the desired result...
But it is very strange that abinit not enough a 8x8x8 k-mesh, in wien2k i did calculate with same parameters
